### ISSUE TITLE
[FEAT] 1주차 과제 복습

### ISSUE THREAD

**Issue by chaentopia** [chaentopia/IN_SOPT_review#1]
## 🍀 Issue

modal과 navigation으로 카카오톡 로그인 화면 구현

## 🏁 To-do

- [x] 로그인 시작 화면 구현
- [x] 새 계정 만들기 화면 구현
- [x] 완료 화면 구현
- [x] 화면 전환 함수 기능 구현
- [x] 데이터 바인딩
